local colors = {
    dark_brown = "#3b3307",
    dark_green = "#142a03",
    dark_red = "#431313",
    dark_yellow = "#4d520d",
    dark0_hard = "#1d2021",
    dark0 = "#282828",
    dark0_soft = "#32302f",
    dark1 = "#3c3836",
    dark2 = "#504945",
    dark3 = "#665c54",
    dark4 = "#7c6f64",
    light_brown = "#fdd69b",
    light_green = "#d5e958",
    light_red = "#ffb3a2",
    light_yellow = "#ffdb57",
    light0_hard = "#f9f5d7",
    light0 = "#fbf1c7",
    light0_soft = "#f2e5bc",
    light1 = "#ebdbb2",
    light2 = "#d5c4a1",
    light3 = "#bdae93",
    light4 = "#a89984",
    bright_red = "#fb4934",
    bright_green = "#b8bb26",
    bright_yellow = "#fabd2f",
    bright_blue = "#83a598",
    bright_purple = "#d3869b",
    bright_aqua = "#8ec07c",
    bright_orange = "#fe8019",
    neutral_red = "#cc241d",
    neutral_green = "#98971a",
    neutral_yellow = "#d79921",
    neutral_blue = "#458588",
    neutral_purple = "#b16286",
    neutral_aqua = "#689d6a",
    neutral_orange = "#d65d0e",
    faded_red = "#9d0006",
    faded_green = "#79740e",
    faded_yellow = "#b57614",
    faded_blue = "#076678",
    faded_purple = "#8f3f71",
    faded_aqua = "#427b58",
    faded_orange = "#af3a03",
    gray = "#928374",
    outerbg = nil,
    innerbg = nil,
}
return {
    "ellisonleao/gruvbox.nvim",
    priority = 1000,
    opts = {
        italic = {
            strings = false,
            operators = false,
            comments = true,
        },
        undercurl = true,
        bold = true,
        invert_selection = false,
        contrast = "hard", -- you can use "soft" or "medium" too
        transparent_mode = true, -- or false if you don't want transparency
        overrides = {
            MatchParen = { bg = "", fg = colors.bright_orange, bold = true },
            Delimiter = { bg = "", fg = colors.light3 },
            LspReferenceText = { underline = true, bold = true },
            LspReferenceRead = { underline = true, bold = true },
            LspReferenceWrite = { underline = true, bold = true },
            Operator = { fg = colors.gray },
            Function = { bg = "", fg = colors.bright_green, bold = false },
            Keyword = { fg = colors.bright_red, italic = true },
            String = { fg = colors.neutral_aqua },
            markdownBold = { bold = true, fg = colors.aqua },
            luaTable = { bg = "", fg = colors.light3 },
            Pmenu = { bg = "NONE" },
            PmenuSel = { bg = "NONE", fg = "#ffffff", bold = true },
            NormalFloat = { bg = "NONE" },
            FloatBorder = { bg = "NONE" },
        },
    },
    config = function(_, opts)
        require("gruvbox").setup(opts)
        vim.cmd.colorscheme("gruvbox")
    end,
}
